To-be-the-best-CSE403/CSE403-To_be_the_best-front

package.json, public/manifest.json, src/content.css, src/content.ts
close #1 
Added the main components of the floating sidebar
=> Add floating sidebar main pane

package.json, public/manifest.json, src/scripts/teambuilder.ts
=> Add ToBeTheBest Pane in Teambuilder

reports/2024-01-31.md
=> Update 2024-01-31 Report Daniel

src/api.ts, src/scripts/teambuilder.ts
=> Add API Request for Teambuilder

.github/workflows/production.yml
=> Add Firefox CI Github Actions

manifest.js
=> Add Extension ID Manifest V3

package-lock.json, package.json, src/pages/content/sidebar/app.test.tsx, src/pages/content/sidebar/app.tsx, test-utils/vitest.setup.js, test/setup.ts, tsconfig.json, vite.config.ts
close #21 
Fix to use jest-dom: https://github.com/testing-library/jest-dom/issues/439
=> Add Extension Sidebar Test

.github/workflows/production.yml
=> Add Test Task CI

package-lock.json, package.json, src/pages/content/injected/app.tsx, src/pages/content/injected/root.tsx
close #25 
- API request for Team creation
- Store Team using packed format in localStorage
- https://github.com/smogon/pokemon-showdown/blob/master/sim/TEAMS.md
- https://github.com/smogon/pokemon-showdown-client/blob/6ed62aa3ecf92b79edc72698e359ad41123910d0/play.pokemonshowdown.com/crossdomain.php#L126
=> Add Team creation and saving

src/pages/content/injected/app.tsx
=> Add Archetype Selection Teambuilder

manifest.js, package.json, src/pages/background/index.ts, src/pages/content/injected/root.tsx
close #29 
- Use Mutation Observer to listen to DOM changes https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver
- Create new tobethebest teampane if not exists
=> Fix Injected Teambuilder Disappearing

src/pages/content/injected/app.tsx
=> Add API Request Teambuilder Archetype

reports/2024-02-07.md
=> Update 2024-02-07 Report

src/pages/content/sidebar/app.css, src/pages/content/sidebar/app.tsx, src/pages/popup/Popup.css, src/pages/popup/Popup.tsx
=> Improve UI Styling Popup and Sidebar

README.md
close #39
- Teambuilder UI
- Teambuilder API
- Teambuilder with Archetype
=> Release v0.1 Teambuilder

src/api.ts, src/pages/content/injected/app.tsx, src/pages/content/sidebar/app.css, src/pages/content/sidebar/app.test.tsx, src/pages/content/sidebar/app.tsx
close #41 
- Improve UI sidebar
- Improve UX Teambuilder by refreshing the page after fetching the team
=> Improve UI/UX Refresh Page When Creating Team

src/pages/content/injected/app.tsx, src/pages/content/sidebar/app.css, src/pages/content/sidebar/app.tsx
=> Improve UI Extension

package-lock.json, package.json, src/api.ts, src/team.ts
=> Include Only Useful Functions From @pkmn/sim Teams API

README.md
close #47 
- Teambuilder with Archetype
=> Release Beta v1.0.0

.gitignore, manifest.js, package.json, src/pages/content/injected/app.tsx, src/pages/content/injected/root.tsx, src/pages/content/sidebar/app.css, src/pages/content/sidebar/app.tsx, src/pages/content/sidebar/root.tsx, src/pages/content/style.scss, tsconfig.json, vite.config.ts
closes #59 
Implement the peer review feedback
- It might be worth updating the UI of your sidebar extension to look more
modern and use more Pokemon-themed colors for greater appeal to users
- Light background
- More colors
=> [Peer Review] Improve UI To look modern with Pokemon-themed colors

package-lock.json, package.json, src/components/HomePage.tsx, src/components/MovePage.tsx, src/pages/content/injected/app.tsx, src/pages/content/sidebar/app.test.tsx, src/pages/content/sidebar/app.tsx, src/pages/content/sidebar/root.tsx, src/pages/content/style.scss, src/protocol/Connection.ts, src/protocol/TeamHandler.tsx, tsconfig.json
=> Add Move Suggestion UI Injection

package-lock.json, package.json, src/components/BattlePage.tsx, src/constants.ts, src/messages.ts, src/pages/content/sidebar/app.tsx, src/pages/content/style.scss, src/pages/main.ts, src/protocol/BattleProtocol.ts, src/sim.ts, types/showdown.d.ts
=> Add Move Suggestion UI With Effectiveness and Damage

src/components/SettingsPage.tsx, src/pages/content/sidebar/app.tsx
=> Add Settings Page

src/components/BattlePage.test.tsx, src/components/BattlePage.tsx, src/components/SettingsPage.test.tsx, src/components/TrainerPage.test.tsx, src/pages/content/style.scss
=> Add Tests Page Components
